added dotenv and secrets validation for apis
aitrail/ait-chat-nodejs-sdk pull request #2
Opened 2024-10-18 11:03 UTC by arunachalamv-cyberinnov

Added dotenv for fetching envs on .env
Added secrets validation for APIs

2025-05-16 12:16 UTC, sathish-cyberinnov reviewed
Read me updated and Routes are checked before redirecting

2025-06-06 05:52 UTC, tdkiran requested changes

2025-06-06 05:52 UTC, tdkiran commented on index.js
> +      `[HPM] Missing "target" option. Ensure the environment variable for ${pathPrefix} is set.`
What's HPM?

2025-06-06 05:52 UTC, tdkiran commented on package.json
>      "http-proxy-middleware": "^3.0.0"
Move http proxy middleware to dependencies

2025-06-06 05:52 UTC, tdkiran commented on README.md
> +app.listen(3000, () => {
Let's remove this section of readme

2025-06-06 05:52 UTC, tdkiran commented on README.md
> +import express from 'express';
Let's make express a pre requisite

2025-06-06 13:32 UTC, sathish-cyberinnov commented on README.md
> +import express from 'express';
New section Prerequisite has been added

2025-06-06 13:33 UTC, sathish-cyberinnov commented on package.json
>      "http-proxy-middleware": "^3.0.0"
Moved "http-proxy-middleware" to dependencies.
"express" and "dotenv" has been listed under peerDependencies

2025-06-06 14:17 UTC, sathish-cyberinnov commented on index.js
> +      `[HPM] Missing "target" option. Ensure the environment variable for ${pathPrefix} is set.`
It Stands for Http proxy middleware

2025-06-06 14:18 UTC, merged